### ISSUE TITLE
issue with chromadb not working 

### ISSUE THREAD

**Issue by 0xYc0d0ne** [SillyTavern/SillyTavern-extras#100]
here is how i got the error 

PS C:\Users\User\SillyTavern-extras> python server.py --enable-modules=chromadb --share --secure

Using torch device: cpu
Initializing ChromaDB
Traceback (most recent call last):
  File "C:\Users\alpha\SillyTavern-extras\server.py", line 268, in <module>
    chromadb_client = chromadb.PersistentClient(path=args.chroma_folder, settings=Settings(anonymized_telemetry=False))
AttributeError: module 'chromadb' has no attribute 'PersistentClient'

please fix this issue

**Comment by Sorro123** [comment]
Run `pip install --upgrade chromadb`

**Comment by wereretot** [comment]
Got this error fixed with @Sorro123 solution.

**Comment by 0xYc0d0ne** [comment]
@Sorro123 i ran this command which got it to run but when actually trying to use chromadb i get errors like this


"127.0.0.1 - - [01/Aug/2023 12:52:35] "POST /api/chromadb/purge HTTP/1.1" 500 -
127.0.0.1 - - [01/Aug/2023 12:52:58] "OPTIONS /api/chromadb/purge HTTP/1.1" 200 -
[2023-08-01 12:52:59,192] ERROR in app: Exception on /api/chromadb/purge [POST]
Traceback (most recent call last):
File "C:\Users\alpha\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\alpha\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\alpha\AppData\Roaming\Python\Python310\site-packages\flask_cors\extension.py", line 165, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "C:\Users\alpha\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\alpha\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "C:\Users\alpha\SillyTavern-extras\server.py", line 303, in decorated_view
return fn(*args, **kwargs)
File "C:\Users\alpha\SillyTavern-extras\server.py", line 775, in chromadb_purge
chromadb_client.persist()
AttributeError: 'SegmentAPI' object has no attribute 'persist'
127.0.0.1 - - [01/Aug/2023 12:52:59] "POST /api/chromadb/purge HTTP/1.1" 500 -"
