### ISSUE TITLE
[BUG] RVC 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by IkariDevGIT** [SillyTavern/SillyTavern-extras#118]
I dont really know what that error is so ill just post it in here(It happens everytime):

```
2023-08-11 12:28:43 | INFO | werkzeug | 192.168.178.53 - - [11/Aug/2023 12:28:43] "OPTIONS /api/edge-tts/generate HTTP/1.1" 200 -
2023-08-11 12:28:43 | INFO | werkzeug | 192.168.178.53 - - [11/Aug/2023 12:28:43] "POST /api/edge-tts/generate HTTP/1.1" 200 -
2023-08-11 12:28:43 | INFO | werkzeug | 192.168.178.53 - - [11/Aug/2023 12:28:43] "OPTIONS /api/voice-conversion/rvc/process-audio HTTP/1.1" 200 -
<RVC module> received: <FileStorage: 'record' ('audio/mpeg')>
<RVC module> Received audio conversion request with model Junko-Professor
<RVC module> loading data/models/rvc/Junko-Professor.pth
<RVC module> Check for index file data/models/rvc/Junko-Professor.index
<RVC module> no index file found, proceeding without index
Traceback (most recent call last):
  File "D:\SillyTavern\new\SillyTavern-extras\modules\voice_conversion\rvc\rvc.py", line 155, in load_audio
    .run(input=audio_source.read(), cmd=["ffmpeg", "-nostdin"], capture_stdout=True, capture_stderr=True)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SillyTavern\new\extrasenv\Lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
              ^^^^^^^^^^
  File "D:\SillyTavern\new\extrasenv\Lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
           ^^^^^^^^^^^^^^^^^
  File "D:\SillyTavern\new\extrasenv\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "D:\SillyTavern\new\extrasenv\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SillyTavern\new\SillyTavern-extras\modules\voice_conversion\rvc\rvc.py", line 210, in vc_single
    audio = load_audio(input_audio_path, 16000)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SillyTavern\new\SillyTavern-extras\modules\voice_conversion\rvc\rvc.py", line 161, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: [WinError 2] Das System kann die angegebene Datei nicht finden

'NoneType' object has no attribute 'dtype'
2023-08-11 12:28:43 | INFO | werkzeug | 192.168.178.53 - - [11/Aug/2023 12:28:43] "POST /api/voice-conversion/rvc/process-audio HTTP/1.1" 500 -
```

**Comment by Ktrcoyote** [comment]
I just pulled the Neo and I'm getting the same error with NovelAI, Coqui and Edge

<RVC module> received: <FileStorage: 'record' ('audio/mpeg')>
<RVC module> Received audio conversion request with model EllieP2
<RVC module> loading data/models/rvc/EllieP2.pth
<RVC module> Check for index file data/models/rvc/EllieP2.index
Traceback (most recent call last):
  File "C:\Users\ktrco\SillyTavern-extras\modules\voice_conversion\rvc\rvc.py", line 153, in load_audio
    ffmpeg.input("pipe:0", threads=0)
    ^^^^^^^^^^^^
AttributeError: module 'ffmpeg' has no attribute 'input'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ktrco\SillyTavern-extras\modules\voice_conversion\rvc\rvc.py", line 210, in vc_single
    audio = load_audio(input_audio_path, 16000)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ktrco\SillyTavern-extras\modules\voice_conversion\rvc\rvc.py", line 161, in load_audio
    raise RuntimeError(f"Failed to load audio: {e}")
RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'

'NoneType' object has no attribute 'dtype'
