### ISSUE TITLE
RVC module not working (No module named 'fairseq')

### ISSUE THREAD

**Issue by xNissX233** [SillyTavern/SillyTavern-Extras#147]
Installed all requirements and rvc requirements, when trying to run extras it crashes with error:
```

Initializing RVC voice conversion (from ST request file)
Increasing server upload limit
Traceback (most recent call last):
  File "/run/media/ruben/Prime/CharacterAI/oobabooga_linux/SillyTavern-extras/SillyTavern-extras/server.py", line 384, in <module>
    import modules.voice_conversion.rvc_module as rvc_module
  File "/run/media/ruben/Prime/CharacterAI/oobabooga_linux/SillyTavern-extras/SillyTavern-extras/modules/voice_conversion/rvc_module.py", line 23, in <module>
    import modules.voice_conversion.rvc.rvc as rvc
  File "/run/media/ruben/Prime/CharacterAI/oobabooga_linux/SillyTavern-extras/SillyTavern-extras/modules/voice_conversion/rvc/rvc.py", line 18, in <module>
    from fairseq import checkpoint_utils
ModuleNotFoundError: No module named 'fairseq'

```

**Comment by Ph0rk0z** [comment]
obviously didn't install fairseq into env

**Comment by Ph0rk0z** [comment]
Its working for me without python 3.11 or patched fairseq. Just 3.10 and normal fairseq. What stopped working for me was coqui local models and the old version of TTS in requirements is one without bark I think.
