### ISSUE TITLE
changes to requirements-complete.txt to make it work

### ISSUE THREAD

**Issue by eyalgi11** [SillyTavern/SillyTavern-Extras#183]
i needed to change the default file to this to make this work
> numpy
flask
flask-cloudflared
flask-cors
flask-compress
markdown
Pillow
colorama
webuiapi
--extra-index-url https://download.pytorch.org/whl/cu118
torch
torchvision
torchaudio
accelerate>=0.20.3
transformers
diffusers
silero-api-server
chromadb
sentence_transformers
edge-tts

> vosk
sounddevice
openai-whisper

> TTS
fastapi
wxpython; sys_platform == 'win32' or sys_platform == 'darwin'
mecab-python3
unidic-lite
py-espeak-ng
TTS[ja]

**Comment by eyalgi11** [comment]
yea

**Comment by GoAwayNow** [comment]
The conflict comes from TTS requiring numpy 1.22.0 exactly while some others require 1.22.5 minimum. Under python 3.10, TTS always requires 1.22.0, so this seems to result in older versions of some other packages being installed.

**Comment by rosx27** [comment]
lib installation takes too long. but i hope this fixes the issue.

**Comment by rosx27** [comment]
i think the implementation of chromadb should also be updated, there is a [new version of chromadb](https://docs.trychroma.com/migration#migration-to-0416---november-7-2023), i think the outdated implementation of this is the reason why i get this error:
```
Collection chat-a3e9a2fc0d89d922b32d993ebe1d6863 does not exist.
Collection chat-da9754979ae069dedf0b4f5f169125f7 does not exist.
Collection chat-118306466f01292cff2bc2f77ad0c0d4 does not exist.
192.168.1.2 - - [16/Nov/2023 23:18:01] "POST /api/chromadb/multiquery HTTP/1.1" 200 -
192.168.1.2 - - [16/Nov/2023 23:19:46] "OPTIONS /api/chromadb HTTP/1.1" 200 -
[2023-11-16 23:19:46,058] ERROR in app: Exception on /api/chromadb [POST]
Traceback (most recent call last):
  File "D:\.conda\envs\ext\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\flask_cors\extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\flask\app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\flask\app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\LLM\SillyTavern-extras\server.py", line 432, in decorated_view
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\AI\LLM\SillyTavern-extras\server.py", line 889, in chromadb_add_messages
    collection = chromadb_client.get_or_create_collection(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\chromadb\api\client.py", line 226, in get_or_create_collection
    return self._server.get_or_create_collection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\chromadb\api\segment.py", line 216, in get_or_create_collection
    return self.create_collection(  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\chromadb\api\segment.py", line 190, in create_collection
    return Collection(
           ^^^^^^^^^^^
  File "D:\.conda\envs\ext\Lib\site-packages\chromadb\api\models\Collection.py", line 85, in __init__
    validate_embedding_function(embedding_function)
  File "D:\.conda\envs\ext\Lib\site-packages\chromadb\api\types.py", line 210, in validate_embedding_function
    raise ValueError(
ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'args', 'kwargs'])
Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface.
Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023
```

**Comment by rosx27** [comment]
that was quick. anyway, i'll pull your updates now and test it. 

> And coqui still sucks, at least as a package to work with

haha yeah? i've only used silero-server, never tried other tts yet. i was hoping to give it a try since i now have some time to tinker with tts due to work.

**Comment by GoAwayNow** [comment]
Should ChromaDB be versioned in the requirements? The migration logs on the site are only a few months apart, there could be some risk of it making breaking changes again before long.

**Comment by rosx27** [comment]
> Should ChromaDB be versioned in the requirements? The migration logs on the site are only a few months apart, there could be some risk of it making breaking changes again before long.

i think so, since the changes were to address multi modal embeddings and I think that's a way to go, and the risk of revising, and possibly breaking the revised implementation due to another update in the future should be acceptable since the current implementation of chromadb is not working.

anyway, here's my update on the current commit [51a6809]:
the chroma API posts, however, retrieval via manual export of the json file or automatic retrieval is not working and giving me an error "chat history [---] not found." or something, I'll update this later when I get home.

**Comment by GoAwayNow** [comment]
So, I'm running in a modified version of the Colab with ChromaDB persistence via Google Drive, and the current commit + latest chromadb works fine for me. Notably, though, I got similar errors before extras was updated for the latest chromadb versions. Specifically, I got those errors because I ran with the new version of chromadb, and then tried to roll back to 0.4.10, but my chromadb.sqlite3 had been changed.
