### ISSUE TITLE
Error 500 RVC not working

### ISSUE THREAD

**Issue by alastor367** [SillyTavern/SillyTavern-Extras#240]
_P.S. I used a translator to translate my problem from my language into English_

I'm using Windows 10

For some reason, when I try to use rvc it crashes in my console with such an error (given below) and on the same page error 500 does anyone know how to fix it? (I've checked the topic and even the topics with the same blend, nothing helped me from what I've seen)

> AttributeError: module 'ffmpeg' has no attribute 'input'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 210, in vc_single
>     audio = load_audio(input_audio_path, 16000)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 161, in load_audio
>     raise RuntimeError(f"Failed to load audio: {e}")
> RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'
> 
> 'NoneType' object has no attribute 'dtype'
> 2024-04-30 19:24:03 | INFO | werkzeug | 127.0.0.1 - - [30/Apr/2024 19:24:03] "POST /api/voice-conversion/rvc/process-audio HTTP/1.1" 500 -
> gin_channels: 256 self.spk_embed_dim: 109
> <All keys matched successfully>
> Traceback (most recent call last):
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 153, in load_audio
>     ffmpeg.input("pipe:0", threads=0)
>     ^^^^^^^^^^^^
> AttributeError: module 'ffmpeg' has no attribute 'input'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 210, in vc_single
>     audio = load_audio(input_audio_path, 16000)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\birdb\Desktop\AI\SillyTavern-Extras-main\modules\voice_conversion\rvc\rvc.py", line 161, in load_audio
>     raise RuntimeError(f"Failed to load audio: {e}")
> RuntimeError: Failed to load audio: module 'ffmpeg' has no attribute 'input'
> 
> 'NoneType' object has no attribute 'dtype'
> 2024-04-30 19:24:04 | INFO | werkzeug | 127.0.0.1 - - [30/Apr/2024 19:24:04] "POST /api/voice-conversion/rvc/process-audio HTTP/1.1" 500 -

**Comment by Sabaknn** [comment]
dude，u’ve solve this problem yet? I got the same problem as well

**Comment by faisalbinali12** [comment]
**### Same Issue**



  File "D:\anaconda3\envs\xtras\Lib\site-packages\torch\serialization.py", line 1470, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, do those steps only if you trust the source of the checkpoint.
        (1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
        (2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
        WeightsUnpickler error: Unsupported global: GLOBAL fairseq.data.dictionary.Dictionary was not an allowed global by default. Please use `torch.serialization.add_safe_globals([Dictionary])` or the `torch.serialization.safe_globals([Dictionary])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.

'NoneType' object has no attribute 'dtype'
2025-02-07 05:46:33 | INFO | werkzeug | 127.0.0.1 - - [07/Feb/2025 05:46:33] "POST /api/voice-conversion/rvc/process-audio HTTP/1.1" 500 -

**Comment by Cohee1207** [comment]
Extras are not maintained anymore, so please consider other alternatives such as https://github.com/daswer123/rvc-python
