### ISSUE TITLE
Chromadb fix

### ISSUE THREAD

**Issue by SpaceDuck41** [SillyTavern/SillyTavern-extras#97]
For anyone having issue with the chromadb error, just change the code in the google collab from “import subprocess”(managed to fix it using chatgpt) to this one: 

import subprocess

# ---
# SillyTavern extras
extras_url = '(disabled)'
params = []
if use_cpu:
    params.append('--cpu')
if use_sd_cpu:
    params.append('--sd-cpu')
if secure:
    params.append('--secure')
params.append('--share')
ExtrasModules = []

if (extras_enable_captioning):
    ExtrasModules.append('caption')

if (extras_enable_memory):
    ExtrasModules.append('summarize')

if (extras_enable_emotions):
    ExtrasModules.append('classify')

if (extras_enable_sd):
    ExtrasModules.append('sd')

if (extras_enable_silero_tts):
    ExtrasModules.append('silero-tts')

if extras_enable_edge_tts:
    ExtrasModules.append('edge-tts')

if (extras_enable_chromadb):
    # Install the chromadb module
    !pip install chromadb
    
    # Import and initialize ChromaDB
    import chromadb
    client = chromadb.PersistentClient(path="/content/drive/My Drive/chromadb_directory/")
    ExtrasModules.append('chromadb')

**Comment by donlinglok** [comment]
seems fixed in [https://github.com/SillyTavern/SillyTavern-extras/commit/38b6403ca1bbe6da896975fafb0d2cdf1ee96198](url)

**Comment by valden80** [comment]
I too getting error form chromaDB startup after the last update:
```
2023-08-01 12:39:16.825799: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-01 12:39:17.426976: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Using torch device: cpu
Initializing an image captioning model...
Initializing a text summarization model...
Initializing a sentiment classification pipeline...
Initializing ChromaDB
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/AI/SillyTavern-extras/server.py:268 in <module>                                            │
│                                                                                                  │
│   265 │   posthog.capture = lambda *args, **kwargs: None                                         │
│   266 │   if args.chroma_host is None:                                                           │
│   267 │   │   if args.chroma_persist:                                                            │
│ ❱ 268 │   │   │   chromadb_client = chromadb.PersistentClient(path=args.chroma_folder, setting   │
│   269 │   │   │   print(f"ChromaDB is running in-memory with persistence. Persistence is store   │
│   270 │   │   else:                                                                              │
│   271 │   │   │   chromadb_client = chromadb.EphemeralClient(Settings(anonymized_telemetry=Fal   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'chromadb' has no attribute 'PersistentClient'
ERROR conda.cli.main_run:execute(47): `conda run python server.py --cpu --enable-modules=caption,summarize,classify,chromadb --listen` failed. (See above for error)
```

**Comment by Wolf1030** [comment]
>@valden80 Chroma broke reverse compatibility in their Python API. You need to update Chroma in your env: `pip install --upgrade chromadb `

This resolved the issue for me. thanks

**Comment by EriIaz** [comment]
> @RBNXI There would likely be problems with that. I suggest installing into a separate environment. @valden80 Chroma broke reverse compatibility in their Python API. You need to update Chroma in your env: `pip install --upgrade chromadb `
Still fails. Now it gives me this error 

```
(extras) D:\NeuralNetworks\SillyTavern-extras>python server.py --listen --enable-modules=chromadb
Using torch device: cpu
Initializing ChromaDB
Traceback (most recent call last):
  File "D:\NeuralNetworks\SillyTavern-extras\server.py", line 268, in <module>
    chromadb_client = chromadb.PersistentClient(path=args.chroma_folder, settings=Settings(anonymized_telemetry=False))
  File "C:\Users\renar\.conda\envs\extras\lib\site-packages\chromadb\__init__.py", line 73, in PersistentClient
    return Client(settings)
  File "C:\Users\renar\.conda\envs\extras\lib\site-packages\chromadb\__init__.py", line 110, in Client
    api = system.instance(API)
  File "C:\Users\renar\.conda\envs\extras\lib\site-packages\chromadb\config.py", line 195, in instance
    impl = type(self)
  File "C:\Users\renar\.conda\envs\extras\lib\site-packages\chromadb\api\segment.py", line 82, in __init__
    self._manager = self.require(SegmentManager)
  File "C:\Users\renar\.conda\envs\extras\lib\site-packages\chromadb\config.py", line 134, in require
    inst = self._system.instance(type)
  File "C:\Users\renar\.conda\envs\extras\lib\site-packages\chromadb\config.py", line 195, in instance
    impl = type(self)
  File "C:\Users\renar\.conda\envs\extras\lib\site-packages\chromadb\segment\impl\manager\local.py", line 73, in __init__
    // PersistentLocalHnswSegment.get_file_handle_count()
  File "C:\Users\renar\.conda\envs\extras\lib\site-packages\chromadb\segment\impl\vector\local_persistent_hnsw.py", line 398, in get_file_handle_count
    hnswlib_count = hnswlib.Index.file_handle_count
AttributeError: type object 'hnswlib.Index' has no attribute 'file_handle_count'

(extras) D:\NeuralNetworks\SillyTavern-extras>

```

Used to work well before the initial faulty change.

**Comment by EriIaz** [comment]
> Try removing your conda env and reinstalling. There may be a conflict in hnswlib previously installed via conda

I've already did that before the original reply. Reinstalled the environment strictly following the guide, except for omitting cloning the SillyTavern-extras with git and I've also run pip install -r requirements-complete.txt at the end. Got the issue. Tried the same without the complete requirements, only chromadb, nltk and scikit-learn, run into the same issue.

**Comment by FitzWM** [comment]
I'm getting the same bug when trying to run Extras with ChromaDB. It happens on both old env and on a brand new env, both with the version of chromadb installed by requirements-complete.txt and the version from upgrading it via pip. Given that parts of the install seem to be moving to Python 3.11 - and that the program itself now complains about wanting 3.11 when it is run - I'm not even 100% sure that the installation steps are actually correct anymore. But I don't know enough about Conda and Python to really have any idea.

**Comment by FitzWM** [comment]
> If you have troubles with local install - run Extras from colab

What if I...don't want to do that? I run everything - SillyTavern, various backends, StableDiffusion and various frontends, PrivateGPT, etc. - locally, without any issue. Until the recent changes to ChromaDB, I did the same with SillyTavern-extras. I get that it's a community project, but the response to "the local install seems to be broken after an update, even following the official instructions" shouldn't be "use the remote version because it actually works."

**Comment by FitzWM** [comment]
>I made fresh conda install just today and it runs fine if we ignore the python upgrade recommendation.

Can I ask how exactly you did this? I'm not doubting you, but I just followed the instructions on the main page a few minutes ago to make a completely new env, and I get the same error with that one. It's using Python 3.10 and the version of ChromaDB installed by requirements-complete.txt - although upgrading ChromaDB via pip doesn't help, either.

**Comment by FitzWM** [comment]
Sadly, no. I tried it both in my old env and in a brand-new one made using the instructions on the main page here.

**Comment by FitzWM** [comment]
No joy, unfortunately. The remove command told me that hnswlib couldn't be found in the target environment, and the install command reported that chroma-hnswlib was already installed. Same thing with both my old env and my fresh one.

I'm honestly really confused, since creating a fresh new env should give me a completely clean slate, right? Meaning that, if it works for other people here, it should work for me. But that doesn't seem to be the case...
